apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-deployment
  namespace: my-app
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 436894295513.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306