apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: my-app
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 436894295513.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
      ports:
        - containerPort: 3306
