apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: my-app
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 436894295513.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
          env:
            - name: DBHOST
              value: mysql-service
            - name: DBUSER
              value: root
            - name: DBPORT
              value: "3306"
            - name: DATABASE
              value: employees
            - name: DBPWD
              value: password
          ports:
            - containerPort: 8080