apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: my-app
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
